### PR TITLE
prepare files for huggingface

### PR DESCRIPTION
**Pull request by cstorm125**
Scrape the tweets (as detailed in `process_huggingface.ipynb`) and format the files to add for huggingface/datasets (`data.zip`)

File also uploaded to https://archive.org/details/ThaiToxicityTweetCorpus

### CODE REVIEW

**Comment by cstorm125** [comment]
huggingface/datasets PR for reference: https://github.com/huggingface/datasets/pull/1448

**Comment by mamorlis** [comment]
Thanks for your contribution! We intentionally do not include the original tweets (because we are not allowed to redistribute the tweets themselves), so we are happy to merge your notebook to scrape the data but we are afraid we do not want to include the tweets.

**Comment by cstorm125** [comment]
@mamorlis Got it. Note that some tweets (506 of them to be exact) are not available to the public anymore at this point (Dec 2020).

**Comment by mamorlis** [comment]
@cstorm125 Thanks! Yes, tweets are known to become unavailable over years (about several % per year). We keep the original texts for reproducibility, so if you need them please let us know (we do not re-distribute them publicly but we can share our copy for research purpose).

**Pull request merged**
